---
# Federated setup
num_rounds: 1
num_total_clients: 10
num_clients_per_round: 2
num_evaluate_clients_per_round: 2

# If clients should be sampled with replacement
# when the dataset is not large enough
enable_resampling: false

# Client resources
cpus_per_client: 10
gpus_per_client: 1

# Seed for client selection
seed: 1337

# Settings for loading the initial parameters 
# used by the server

# If the server should try to load saved parameters, if it fails it will do the normal procedure of generating a random net
# Leave on as true in case you need to enable checkpointing later on
load_saved_parameters: true
# The round from which to load the parameters
# if null it will load the most recent round
parameters_round: null

# Path to the folder where the parameters are located, leave null if you want to use automatic detecting with the next option
parameters_folder: null

# If reusing an output directory for checkpointing
# it will automatically load the requested round from results/parameters
# Leave as true unless you want to customise this behaviour
use_results_dir: true
